version: '3'
services:
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: python_container
    volumes:
      - ${PWD}/src/:/var/www/python/
    tty: true